# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.20.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.20.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/alexandrejosien/Desktop/SoundHook

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/alexandrejosien/Desktop/SoundHook

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.20.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.20.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/alexandrejosien/Desktop/SoundHook/CMakeFiles /Users/alexandrejosien/Desktop/SoundHook//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/alexandrejosien/Desktop/SoundHook/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TESTGRAPH

# Build rule for target.
TESTGRAPH: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TESTGRAPH
.PHONY : TESTGRAPH

# fast build rule for target.
TESTGRAPH/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TESTGRAPH.dir/build.make CMakeFiles/TESTGRAPH.dir/build
.PHONY : TESTGRAPH/fast

#=============================================================================
# Target rules for targets named mainUI

# Build rule for target.
mainUI: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mainUI
.PHONY : mainUI

# fast build rule for target.
mainUI/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/build
.PHONY : mainUI/fast

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

GUI/type/types.o: GUI/type/types.c.o
.PHONY : GUI/type/types.o

# target to build an object file
GUI/type/types.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/GUI/type/types.c.o
.PHONY : GUI/type/types.c.o

GUI/type/types.i: GUI/type/types.c.i
.PHONY : GUI/type/types.i

# target to preprocess a source file
GUI/type/types.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/GUI/type/types.c.i
.PHONY : GUI/type/types.c.i

GUI/type/types.s: GUI/type/types.c.s
.PHONY : GUI/type/types.s

# target to generate assembly for a file
GUI/type/types.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/GUI/type/types.c.s
.PHONY : GUI/type/types.c.s

GUI/ui_src/DrawSoundPreview.o: GUI/ui_src/DrawSoundPreview.c.o
.PHONY : GUI/ui_src/DrawSoundPreview.o

# target to build an object file
GUI/ui_src/DrawSoundPreview.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/GUI/ui_src/DrawSoundPreview.c.o
.PHONY : GUI/ui_src/DrawSoundPreview.c.o

GUI/ui_src/DrawSoundPreview.i: GUI/ui_src/DrawSoundPreview.c.i
.PHONY : GUI/ui_src/DrawSoundPreview.i

# target to preprocess a source file
GUI/ui_src/DrawSoundPreview.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/GUI/ui_src/DrawSoundPreview.c.i
.PHONY : GUI/ui_src/DrawSoundPreview.c.i

GUI/ui_src/DrawSoundPreview.s: GUI/ui_src/DrawSoundPreview.c.s
.PHONY : GUI/ui_src/DrawSoundPreview.s

# target to generate assembly for a file
GUI/ui_src/DrawSoundPreview.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/GUI/ui_src/DrawSoundPreview.c.s
.PHONY : GUI/ui_src/DrawSoundPreview.c.s

GUI/ui_src/EqualizerViewer.o: GUI/ui_src/EqualizerViewer.c.o
.PHONY : GUI/ui_src/EqualizerViewer.o

# target to build an object file
GUI/ui_src/EqualizerViewer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/GUI/ui_src/EqualizerViewer.c.o
.PHONY : GUI/ui_src/EqualizerViewer.c.o

GUI/ui_src/EqualizerViewer.i: GUI/ui_src/EqualizerViewer.c.i
.PHONY : GUI/ui_src/EqualizerViewer.i

# target to preprocess a source file
GUI/ui_src/EqualizerViewer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/GUI/ui_src/EqualizerViewer.c.i
.PHONY : GUI/ui_src/EqualizerViewer.c.i

GUI/ui_src/EqualizerViewer.s: GUI/ui_src/EqualizerViewer.c.s
.PHONY : GUI/ui_src/EqualizerViewer.s

# target to generate assembly for a file
GUI/ui_src/EqualizerViewer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/GUI/ui_src/EqualizerViewer.c.s
.PHONY : GUI/ui_src/EqualizerViewer.c.s

GUI/ui_src/SliderTagert.o: GUI/ui_src/SliderTagert.c.o
.PHONY : GUI/ui_src/SliderTagert.o

# target to build an object file
GUI/ui_src/SliderTagert.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/GUI/ui_src/SliderTagert.c.o
.PHONY : GUI/ui_src/SliderTagert.c.o

GUI/ui_src/SliderTagert.i: GUI/ui_src/SliderTagert.c.i
.PHONY : GUI/ui_src/SliderTagert.i

# target to preprocess a source file
GUI/ui_src/SliderTagert.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/GUI/ui_src/SliderTagert.c.i
.PHONY : GUI/ui_src/SliderTagert.c.i

GUI/ui_src/SliderTagert.s: GUI/ui_src/SliderTagert.c.s
.PHONY : GUI/ui_src/SliderTagert.s

# target to generate assembly for a file
GUI/ui_src/SliderTagert.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/GUI/ui_src/SliderTagert.c.s
.PHONY : GUI/ui_src/SliderTagert.c.s

GUI/ui_src/SoundPlay.o: GUI/ui_src/SoundPlay.c.o
.PHONY : GUI/ui_src/SoundPlay.o

# target to build an object file
GUI/ui_src/SoundPlay.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/GUI/ui_src/SoundPlay.c.o
.PHONY : GUI/ui_src/SoundPlay.c.o

GUI/ui_src/SoundPlay.i: GUI/ui_src/SoundPlay.c.i
.PHONY : GUI/ui_src/SoundPlay.i

# target to preprocess a source file
GUI/ui_src/SoundPlay.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/GUI/ui_src/SoundPlay.c.i
.PHONY : GUI/ui_src/SoundPlay.c.i

GUI/ui_src/SoundPlay.s: GUI/ui_src/SoundPlay.c.s
.PHONY : GUI/ui_src/SoundPlay.s

# target to generate assembly for a file
GUI/ui_src/SoundPlay.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/GUI/ui_src/SoundPlay.c.s
.PHONY : GUI/ui_src/SoundPlay.c.s

GUI/ui_src/uiInit.o: GUI/ui_src/uiInit.c.o
.PHONY : GUI/ui_src/uiInit.o

# target to build an object file
GUI/ui_src/uiInit.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/GUI/ui_src/uiInit.c.o
.PHONY : GUI/ui_src/uiInit.c.o

GUI/ui_src/uiInit.i: GUI/ui_src/uiInit.c.i
.PHONY : GUI/ui_src/uiInit.i

# target to preprocess a source file
GUI/ui_src/uiInit.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/GUI/ui_src/uiInit.c.i
.PHONY : GUI/ui_src/uiInit.c.i

GUI/ui_src/uiInit.s: GUI/ui_src/uiInit.c.s
.PHONY : GUI/ui_src/uiInit.s

# target to generate assembly for a file
GUI/ui_src/uiInit.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/GUI/ui_src/uiInit.c.s
.PHONY : GUI/ui_src/uiInit.c.s

GUI/ui_src/uiTarget.o: GUI/ui_src/uiTarget.c.o
.PHONY : GUI/ui_src/uiTarget.o

# target to build an object file
GUI/ui_src/uiTarget.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/GUI/ui_src/uiTarget.c.o
.PHONY : GUI/ui_src/uiTarget.c.o

GUI/ui_src/uiTarget.i: GUI/ui_src/uiTarget.c.i
.PHONY : GUI/ui_src/uiTarget.i

# target to preprocess a source file
GUI/ui_src/uiTarget.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/GUI/ui_src/uiTarget.c.i
.PHONY : GUI/ui_src/uiTarget.c.i

GUI/ui_src/uiTarget.s: GUI/ui_src/uiTarget.c.s
.PHONY : GUI/ui_src/uiTarget.s

# target to generate assembly for a file
GUI/ui_src/uiTarget.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/GUI/ui_src/uiTarget.c.s
.PHONY : GUI/ui_src/uiTarget.c.s

GUI/ui_tools/UITools.o: GUI/ui_tools/UITools.c.o
.PHONY : GUI/ui_tools/UITools.o

# target to build an object file
GUI/ui_tools/UITools.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/GUI/ui_tools/UITools.c.o
.PHONY : GUI/ui_tools/UITools.c.o

GUI/ui_tools/UITools.i: GUI/ui_tools/UITools.c.i
.PHONY : GUI/ui_tools/UITools.i

# target to preprocess a source file
GUI/ui_tools/UITools.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/GUI/ui_tools/UITools.c.i
.PHONY : GUI/ui_tools/UITools.c.i

GUI/ui_tools/UITools.s: GUI/ui_tools/UITools.c.s
.PHONY : GUI/ui_tools/UITools.s

# target to generate assembly for a file
GUI/ui_tools/UITools.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/GUI/ui_tools/UITools.c.s
.PHONY : GUI/ui_tools/UITools.c.s

GraphTools/Graph.o: GraphTools/Graph.c.o
.PHONY : GraphTools/Graph.o

# target to build an object file
GraphTools/Graph.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/GraphTools/Graph.c.o
.PHONY : GraphTools/Graph.c.o

GraphTools/Graph.i: GraphTools/Graph.c.i
.PHONY : GraphTools/Graph.i

# target to preprocess a source file
GraphTools/Graph.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/GraphTools/Graph.c.i
.PHONY : GraphTools/Graph.c.i

GraphTools/Graph.s: GraphTools/Graph.c.s
.PHONY : GraphTools/Graph.s

# target to generate assembly for a file
GraphTools/Graph.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/GraphTools/Graph.c.s
.PHONY : GraphTools/Graph.c.s

GraphTools/pbPlots.o: GraphTools/pbPlots.c.o
.PHONY : GraphTools/pbPlots.o

# target to build an object file
GraphTools/pbPlots.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/GraphTools/pbPlots.c.o
.PHONY : GraphTools/pbPlots.c.o

GraphTools/pbPlots.i: GraphTools/pbPlots.c.i
.PHONY : GraphTools/pbPlots.i

# target to preprocess a source file
GraphTools/pbPlots.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/GraphTools/pbPlots.c.i
.PHONY : GraphTools/pbPlots.c.i

GraphTools/pbPlots.s: GraphTools/pbPlots.c.s
.PHONY : GraphTools/pbPlots.s

# target to generate assembly for a file
GraphTools/pbPlots.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/GraphTools/pbPlots.c.s
.PHONY : GraphTools/pbPlots.c.s

GraphTools/supportLib.o: GraphTools/supportLib.c.o
.PHONY : GraphTools/supportLib.o

# target to build an object file
GraphTools/supportLib.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/GraphTools/supportLib.c.o
.PHONY : GraphTools/supportLib.c.o

GraphTools/supportLib.i: GraphTools/supportLib.c.i
.PHONY : GraphTools/supportLib.i

# target to preprocess a source file
GraphTools/supportLib.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/GraphTools/supportLib.c.i
.PHONY : GraphTools/supportLib.c.i

GraphTools/supportLib.s: GraphTools/supportLib.c.s
.PHONY : GraphTools/supportLib.s

# target to generate assembly for a file
GraphTools/supportLib.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/GraphTools/supportLib.c.s
.PHONY : GraphTools/supportLib.c.s

decomposition/Treat/Treat.o: decomposition/Treat/Treat.c.o
.PHONY : decomposition/Treat/Treat.o

# target to build an object file
decomposition/Treat/Treat.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/decomposition/Treat/Treat.c.o
.PHONY : decomposition/Treat/Treat.c.o

decomposition/Treat/Treat.i: decomposition/Treat/Treat.c.i
.PHONY : decomposition/Treat/Treat.i

# target to preprocess a source file
decomposition/Treat/Treat.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/decomposition/Treat/Treat.c.i
.PHONY : decomposition/Treat/Treat.c.i

decomposition/Treat/Treat.s: decomposition/Treat/Treat.c.s
.PHONY : decomposition/Treat/Treat.s

# target to generate assembly for a file
decomposition/Treat/Treat.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/decomposition/Treat/Treat.c.s
.PHONY : decomposition/Treat/Treat.c.s

decomposition/Treat/equalizer.o: decomposition/Treat/equalizer.c.o
.PHONY : decomposition/Treat/equalizer.o

# target to build an object file
decomposition/Treat/equalizer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/decomposition/Treat/equalizer.c.o
.PHONY : decomposition/Treat/equalizer.c.o

decomposition/Treat/equalizer.i: decomposition/Treat/equalizer.c.i
.PHONY : decomposition/Treat/equalizer.i

# target to preprocess a source file
decomposition/Treat/equalizer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/decomposition/Treat/equalizer.c.i
.PHONY : decomposition/Treat/equalizer.c.i

decomposition/Treat/equalizer.s: decomposition/Treat/equalizer.c.s
.PHONY : decomposition/Treat/equalizer.s

# target to generate assembly for a file
decomposition/Treat/equalizer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/decomposition/Treat/equalizer.c.s
.PHONY : decomposition/Treat/equalizer.c.s

decomposition/Treat/previewEqua.o: decomposition/Treat/previewEqua.c.o
.PHONY : decomposition/Treat/previewEqua.o

# target to build an object file
decomposition/Treat/previewEqua.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/decomposition/Treat/previewEqua.c.o
.PHONY : decomposition/Treat/previewEqua.c.o

decomposition/Treat/previewEqua.i: decomposition/Treat/previewEqua.c.i
.PHONY : decomposition/Treat/previewEqua.i

# target to preprocess a source file
decomposition/Treat/previewEqua.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/decomposition/Treat/previewEqua.c.i
.PHONY : decomposition/Treat/previewEqua.c.i

decomposition/Treat/previewEqua.s: decomposition/Treat/previewEqua.c.s
.PHONY : decomposition/Treat/previewEqua.s

# target to generate assembly for a file
decomposition/Treat/previewEqua.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/decomposition/Treat/previewEqua.c.s
.PHONY : decomposition/Treat/previewEqua.c.s

decomposition/fft.o: decomposition/fft.c.o
.PHONY : decomposition/fft.o

# target to build an object file
decomposition/fft.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/decomposition/fft.c.o
.PHONY : decomposition/fft.c.o

decomposition/fft.i: decomposition/fft.c.i
.PHONY : decomposition/fft.i

# target to preprocess a source file
decomposition/fft.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/decomposition/fft.c.i
.PHONY : decomposition/fft.c.i

decomposition/fft.s: decomposition/fft.c.s
.PHONY : decomposition/fft.s

# target to generate assembly for a file
decomposition/fft.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/decomposition/fft.c.s
.PHONY : decomposition/fft.c.s

decomposition/main.o: decomposition/main.c.o
.PHONY : decomposition/main.o

# target to build an object file
decomposition/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/decomposition/main.c.o
.PHONY : decomposition/main.c.o

decomposition/main.i: decomposition/main.c.i
.PHONY : decomposition/main.i

# target to preprocess a source file
decomposition/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/decomposition/main.c.i
.PHONY : decomposition/main.c.i

decomposition/main.s: decomposition/main.c.s
.PHONY : decomposition/main.s

# target to generate assembly for a file
decomposition/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/decomposition/main.c.s
.PHONY : decomposition/main.c.s

file_decoder/wav/Decoder/WavDecoder.o: file_decoder/wav/Decoder/WavDecoder.c.o
.PHONY : file_decoder/wav/Decoder/WavDecoder.o

# target to build an object file
file_decoder/wav/Decoder/WavDecoder.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/file_decoder/wav/Decoder/WavDecoder.c.o
.PHONY : file_decoder/wav/Decoder/WavDecoder.c.o

file_decoder/wav/Decoder/WavDecoder.i: file_decoder/wav/Decoder/WavDecoder.c.i
.PHONY : file_decoder/wav/Decoder/WavDecoder.i

# target to preprocess a source file
file_decoder/wav/Decoder/WavDecoder.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/file_decoder/wav/Decoder/WavDecoder.c.i
.PHONY : file_decoder/wav/Decoder/WavDecoder.c.i

file_decoder/wav/Decoder/WavDecoder.s: file_decoder/wav/Decoder/WavDecoder.c.s
.PHONY : file_decoder/wav/Decoder/WavDecoder.s

# target to generate assembly for a file
file_decoder/wav/Decoder/WavDecoder.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/file_decoder/wav/Decoder/WavDecoder.c.s
.PHONY : file_decoder/wav/Decoder/WavDecoder.c.s

file_decoder/wav/Decoder/decoderWavHeader.o: file_decoder/wav/Decoder/decoderWavHeader.c.o
.PHONY : file_decoder/wav/Decoder/decoderWavHeader.o

# target to build an object file
file_decoder/wav/Decoder/decoderWavHeader.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/file_decoder/wav/Decoder/decoderWavHeader.c.o
.PHONY : file_decoder/wav/Decoder/decoderWavHeader.c.o

file_decoder/wav/Decoder/decoderWavHeader.i: file_decoder/wav/Decoder/decoderWavHeader.c.i
.PHONY : file_decoder/wav/Decoder/decoderWavHeader.i

# target to preprocess a source file
file_decoder/wav/Decoder/decoderWavHeader.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/file_decoder/wav/Decoder/decoderWavHeader.c.i
.PHONY : file_decoder/wav/Decoder/decoderWavHeader.c.i

file_decoder/wav/Decoder/decoderWavHeader.s: file_decoder/wav/Decoder/decoderWavHeader.c.s
.PHONY : file_decoder/wav/Decoder/decoderWavHeader.s

# target to generate assembly for a file
file_decoder/wav/Decoder/decoderWavHeader.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/file_decoder/wav/Decoder/decoderWavHeader.c.s
.PHONY : file_decoder/wav/Decoder/decoderWavHeader.c.s

file_decoder/wav/Recoder/WavRecoder.o: file_decoder/wav/Recoder/WavRecoder.c.o
.PHONY : file_decoder/wav/Recoder/WavRecoder.o

# target to build an object file
file_decoder/wav/Recoder/WavRecoder.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/file_decoder/wav/Recoder/WavRecoder.c.o
.PHONY : file_decoder/wav/Recoder/WavRecoder.c.o

file_decoder/wav/Recoder/WavRecoder.i: file_decoder/wav/Recoder/WavRecoder.c.i
.PHONY : file_decoder/wav/Recoder/WavRecoder.i

# target to preprocess a source file
file_decoder/wav/Recoder/WavRecoder.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/file_decoder/wav/Recoder/WavRecoder.c.i
.PHONY : file_decoder/wav/Recoder/WavRecoder.c.i

file_decoder/wav/Recoder/WavRecoder.s: file_decoder/wav/Recoder/WavRecoder.c.s
.PHONY : file_decoder/wav/Recoder/WavRecoder.s

# target to generate assembly for a file
file_decoder/wav/Recoder/WavRecoder.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/file_decoder/wav/Recoder/WavRecoder.c.s
.PHONY : file_decoder/wav/Recoder/WavRecoder.c.s

file_decoder/wav/tools/WavChecker.o: file_decoder/wav/tools/WavChecker.c.o
.PHONY : file_decoder/wav/tools/WavChecker.o

# target to build an object file
file_decoder/wav/tools/WavChecker.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/file_decoder/wav/tools/WavChecker.c.o
.PHONY : file_decoder/wav/tools/WavChecker.c.o

file_decoder/wav/tools/WavChecker.i: file_decoder/wav/tools/WavChecker.c.i
.PHONY : file_decoder/wav/tools/WavChecker.i

# target to preprocess a source file
file_decoder/wav/tools/WavChecker.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/file_decoder/wav/tools/WavChecker.c.i
.PHONY : file_decoder/wav/tools/WavChecker.c.i

file_decoder/wav/tools/WavChecker.s: file_decoder/wav/tools/WavChecker.c.s
.PHONY : file_decoder/wav/tools/WavChecker.s

# target to generate assembly for a file
file_decoder/wav/tools/WavChecker.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/file_decoder/wav/tools/WavChecker.c.s
.PHONY : file_decoder/wav/tools/WavChecker.c.s

file_decoder/wav/tools/WavTools.o: file_decoder/wav/tools/WavTools.c.o
.PHONY : file_decoder/wav/tools/WavTools.o

# target to build an object file
file_decoder/wav/tools/WavTools.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/file_decoder/wav/tools/WavTools.c.o
.PHONY : file_decoder/wav/tools/WavTools.c.o

file_decoder/wav/tools/WavTools.i: file_decoder/wav/tools/WavTools.c.i
.PHONY : file_decoder/wav/tools/WavTools.i

# target to preprocess a source file
file_decoder/wav/tools/WavTools.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/file_decoder/wav/tools/WavTools.c.i
.PHONY : file_decoder/wav/tools/WavTools.c.i

file_decoder/wav/tools/WavTools.s: file_decoder/wav/tools/WavTools.c.s
.PHONY : file_decoder/wav/tools/WavTools.s

# target to generate assembly for a file
file_decoder/wav/tools/WavTools.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/file_decoder/wav/tools/WavTools.c.s
.PHONY : file_decoder/wav/tools/WavTools.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.c.s
.PHONY : main.c.s

mainUI.o: mainUI.c.o
.PHONY : mainUI.o

# target to build an object file
mainUI.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/mainUI.c.o
.PHONY : mainUI.c.o

mainUI.i: mainUI.c.i
.PHONY : mainUI.i

# target to preprocess a source file
mainUI.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/mainUI.c.i
.PHONY : mainUI.c.i

mainUI.s: mainUI.c.s
.PHONY : mainUI.s

# target to generate assembly for a file
mainUI.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/mainUI.c.s
.PHONY : mainUI.c.s

testGraph.o: testGraph.c.o
.PHONY : testGraph.o

# target to build an object file
testGraph.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TESTGRAPH.dir/build.make CMakeFiles/TESTGRAPH.dir/testGraph.c.o
.PHONY : testGraph.c.o

testGraph.i: testGraph.c.i
.PHONY : testGraph.i

# target to preprocess a source file
testGraph.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TESTGRAPH.dir/build.make CMakeFiles/TESTGRAPH.dir/testGraph.c.i
.PHONY : testGraph.c.i

testGraph.s: testGraph.c.s
.PHONY : testGraph.s

# target to generate assembly for a file
testGraph.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TESTGRAPH.dir/build.make CMakeFiles/TESTGRAPH.dir/testGraph.c.s
.PHONY : testGraph.c.s

wavelib/auxiliary/denoise.o: wavelib/auxiliary/denoise.c.o
.PHONY : wavelib/auxiliary/denoise.o

# target to build an object file
wavelib/auxiliary/denoise.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/wavelib/auxiliary/denoise.c.o
.PHONY : wavelib/auxiliary/denoise.c.o

wavelib/auxiliary/denoise.i: wavelib/auxiliary/denoise.c.i
.PHONY : wavelib/auxiliary/denoise.i

# target to preprocess a source file
wavelib/auxiliary/denoise.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/wavelib/auxiliary/denoise.c.i
.PHONY : wavelib/auxiliary/denoise.c.i

wavelib/auxiliary/denoise.s: wavelib/auxiliary/denoise.c.s
.PHONY : wavelib/auxiliary/denoise.s

# target to generate assembly for a file
wavelib/auxiliary/denoise.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/wavelib/auxiliary/denoise.c.s
.PHONY : wavelib/auxiliary/denoise.c.s

wavelib/auxiliary/waux.o: wavelib/auxiliary/waux.c.o
.PHONY : wavelib/auxiliary/waux.o

# target to build an object file
wavelib/auxiliary/waux.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/wavelib/auxiliary/waux.c.o
.PHONY : wavelib/auxiliary/waux.c.o

wavelib/auxiliary/waux.i: wavelib/auxiliary/waux.c.i
.PHONY : wavelib/auxiliary/waux.i

# target to preprocess a source file
wavelib/auxiliary/waux.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/wavelib/auxiliary/waux.c.i
.PHONY : wavelib/auxiliary/waux.c.i

wavelib/auxiliary/waux.s: wavelib/auxiliary/waux.c.s
.PHONY : wavelib/auxiliary/waux.s

# target to generate assembly for a file
wavelib/auxiliary/waux.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/wavelib/auxiliary/waux.c.s
.PHONY : wavelib/auxiliary/waux.c.s

wavelib/src/conv.o: wavelib/src/conv.c.o
.PHONY : wavelib/src/conv.o

# target to build an object file
wavelib/src/conv.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/wavelib/src/conv.c.o
.PHONY : wavelib/src/conv.c.o

wavelib/src/conv.i: wavelib/src/conv.c.i
.PHONY : wavelib/src/conv.i

# target to preprocess a source file
wavelib/src/conv.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/wavelib/src/conv.c.i
.PHONY : wavelib/src/conv.c.i

wavelib/src/conv.s: wavelib/src/conv.c.s
.PHONY : wavelib/src/conv.s

# target to generate assembly for a file
wavelib/src/conv.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/wavelib/src/conv.c.s
.PHONY : wavelib/src/conv.c.s

wavelib/src/cwt.o: wavelib/src/cwt.c.o
.PHONY : wavelib/src/cwt.o

# target to build an object file
wavelib/src/cwt.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/wavelib/src/cwt.c.o
.PHONY : wavelib/src/cwt.c.o

wavelib/src/cwt.i: wavelib/src/cwt.c.i
.PHONY : wavelib/src/cwt.i

# target to preprocess a source file
wavelib/src/cwt.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/wavelib/src/cwt.c.i
.PHONY : wavelib/src/cwt.c.i

wavelib/src/cwt.s: wavelib/src/cwt.c.s
.PHONY : wavelib/src/cwt.s

# target to generate assembly for a file
wavelib/src/cwt.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/wavelib/src/cwt.c.s
.PHONY : wavelib/src/cwt.c.s

wavelib/src/cwtmath.o: wavelib/src/cwtmath.c.o
.PHONY : wavelib/src/cwtmath.o

# target to build an object file
wavelib/src/cwtmath.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/wavelib/src/cwtmath.c.o
.PHONY : wavelib/src/cwtmath.c.o

wavelib/src/cwtmath.i: wavelib/src/cwtmath.c.i
.PHONY : wavelib/src/cwtmath.i

# target to preprocess a source file
wavelib/src/cwtmath.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/wavelib/src/cwtmath.c.i
.PHONY : wavelib/src/cwtmath.c.i

wavelib/src/cwtmath.s: wavelib/src/cwtmath.c.s
.PHONY : wavelib/src/cwtmath.s

# target to generate assembly for a file
wavelib/src/cwtmath.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/wavelib/src/cwtmath.c.s
.PHONY : wavelib/src/cwtmath.c.s

wavelib/src/hsfft.o: wavelib/src/hsfft.c.o
.PHONY : wavelib/src/hsfft.o

# target to build an object file
wavelib/src/hsfft.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/wavelib/src/hsfft.c.o
.PHONY : wavelib/src/hsfft.c.o

wavelib/src/hsfft.i: wavelib/src/hsfft.c.i
.PHONY : wavelib/src/hsfft.i

# target to preprocess a source file
wavelib/src/hsfft.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/wavelib/src/hsfft.c.i
.PHONY : wavelib/src/hsfft.c.i

wavelib/src/hsfft.s: wavelib/src/hsfft.c.s
.PHONY : wavelib/src/hsfft.s

# target to generate assembly for a file
wavelib/src/hsfft.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/wavelib/src/hsfft.c.s
.PHONY : wavelib/src/hsfft.c.s

wavelib/src/real.o: wavelib/src/real.c.o
.PHONY : wavelib/src/real.o

# target to build an object file
wavelib/src/real.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/wavelib/src/real.c.o
.PHONY : wavelib/src/real.c.o

wavelib/src/real.i: wavelib/src/real.c.i
.PHONY : wavelib/src/real.i

# target to preprocess a source file
wavelib/src/real.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/wavelib/src/real.c.i
.PHONY : wavelib/src/real.c.i

wavelib/src/real.s: wavelib/src/real.c.s
.PHONY : wavelib/src/real.s

# target to generate assembly for a file
wavelib/src/real.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/wavelib/src/real.c.s
.PHONY : wavelib/src/real.c.s

wavelib/src/wavefilt.o: wavelib/src/wavefilt.c.o
.PHONY : wavelib/src/wavefilt.o

# target to build an object file
wavelib/src/wavefilt.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/wavelib/src/wavefilt.c.o
.PHONY : wavelib/src/wavefilt.c.o

wavelib/src/wavefilt.i: wavelib/src/wavefilt.c.i
.PHONY : wavelib/src/wavefilt.i

# target to preprocess a source file
wavelib/src/wavefilt.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/wavelib/src/wavefilt.c.i
.PHONY : wavelib/src/wavefilt.c.i

wavelib/src/wavefilt.s: wavelib/src/wavefilt.c.s
.PHONY : wavelib/src/wavefilt.s

# target to generate assembly for a file
wavelib/src/wavefilt.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/wavelib/src/wavefilt.c.s
.PHONY : wavelib/src/wavefilt.c.s

wavelib/src/wavefunc.o: wavelib/src/wavefunc.c.o
.PHONY : wavelib/src/wavefunc.o

# target to build an object file
wavelib/src/wavefunc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/wavelib/src/wavefunc.c.o
.PHONY : wavelib/src/wavefunc.c.o

wavelib/src/wavefunc.i: wavelib/src/wavefunc.c.i
.PHONY : wavelib/src/wavefunc.i

# target to preprocess a source file
wavelib/src/wavefunc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/wavelib/src/wavefunc.c.i
.PHONY : wavelib/src/wavefunc.c.i

wavelib/src/wavefunc.s: wavelib/src/wavefunc.c.s
.PHONY : wavelib/src/wavefunc.s

# target to generate assembly for a file
wavelib/src/wavefunc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/wavelib/src/wavefunc.c.s
.PHONY : wavelib/src/wavefunc.c.s

wavelib/src/wavelib.o: wavelib/src/wavelib.c.o
.PHONY : wavelib/src/wavelib.o

# target to build an object file
wavelib/src/wavelib.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/wavelib/src/wavelib.c.o
.PHONY : wavelib/src/wavelib.c.o

wavelib/src/wavelib.i: wavelib/src/wavelib.c.i
.PHONY : wavelib/src/wavelib.i

# target to preprocess a source file
wavelib/src/wavelib.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/wavelib/src/wavelib.c.i
.PHONY : wavelib/src/wavelib.c.i

wavelib/src/wavelib.s: wavelib/src/wavelib.c.s
.PHONY : wavelib/src/wavelib.s

# target to generate assembly for a file
wavelib/src/wavelib.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/wavelib/src/wavelib.c.s
.PHONY : wavelib/src/wavelib.c.s

wavelib/src/wtmath.o: wavelib/src/wtmath.c.o
.PHONY : wavelib/src/wtmath.o

# target to build an object file
wavelib/src/wtmath.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/wavelib/src/wtmath.c.o
.PHONY : wavelib/src/wtmath.c.o

wavelib/src/wtmath.i: wavelib/src/wtmath.c.i
.PHONY : wavelib/src/wtmath.i

# target to preprocess a source file
wavelib/src/wtmath.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/wavelib/src/wtmath.c.i
.PHONY : wavelib/src/wtmath.c.i

wavelib/src/wtmath.s: wavelib/src/wtmath.c.s
.PHONY : wavelib/src/wtmath.s

# target to generate assembly for a file
wavelib/src/wtmath.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/wavelib/src/wtmath.c.s
.PHONY : wavelib/src/wtmath.c.s

wavlet/Wavelet.o: wavlet/Wavelet.c.o
.PHONY : wavlet/Wavelet.o

# target to build an object file
wavlet/Wavelet.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/wavlet/Wavelet.c.o
.PHONY : wavlet/Wavelet.c.o

wavlet/Wavelet.i: wavlet/Wavelet.c.i
.PHONY : wavlet/Wavelet.i

# target to preprocess a source file
wavlet/Wavelet.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/wavlet/Wavelet.c.i
.PHONY : wavlet/Wavelet.c.i

wavlet/Wavelet.s: wavlet/Wavelet.c.s
.PHONY : wavlet/Wavelet.s

# target to generate assembly for a file
wavlet/Wavelet.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainUI.dir/build.make CMakeFiles/mainUI.dir/wavlet/Wavelet.c.s
.PHONY : wavlet/Wavelet.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... TESTGRAPH"
	@echo "... main"
	@echo "... mainUI"
	@echo "... GUI/type/types.o"
	@echo "... GUI/type/types.i"
	@echo "... GUI/type/types.s"
	@echo "... GUI/ui_src/DrawSoundPreview.o"
	@echo "... GUI/ui_src/DrawSoundPreview.i"
	@echo "... GUI/ui_src/DrawSoundPreview.s"
	@echo "... GUI/ui_src/EqualizerViewer.o"
	@echo "... GUI/ui_src/EqualizerViewer.i"
	@echo "... GUI/ui_src/EqualizerViewer.s"
	@echo "... GUI/ui_src/SliderTagert.o"
	@echo "... GUI/ui_src/SliderTagert.i"
	@echo "... GUI/ui_src/SliderTagert.s"
	@echo "... GUI/ui_src/SoundPlay.o"
	@echo "... GUI/ui_src/SoundPlay.i"
	@echo "... GUI/ui_src/SoundPlay.s"
	@echo "... GUI/ui_src/uiInit.o"
	@echo "... GUI/ui_src/uiInit.i"
	@echo "... GUI/ui_src/uiInit.s"
	@echo "... GUI/ui_src/uiTarget.o"
	@echo "... GUI/ui_src/uiTarget.i"
	@echo "... GUI/ui_src/uiTarget.s"
	@echo "... GUI/ui_tools/UITools.o"
	@echo "... GUI/ui_tools/UITools.i"
	@echo "... GUI/ui_tools/UITools.s"
	@echo "... GraphTools/Graph.o"
	@echo "... GraphTools/Graph.i"
	@echo "... GraphTools/Graph.s"
	@echo "... GraphTools/pbPlots.o"
	@echo "... GraphTools/pbPlots.i"
	@echo "... GraphTools/pbPlots.s"
	@echo "... GraphTools/supportLib.o"
	@echo "... GraphTools/supportLib.i"
	@echo "... GraphTools/supportLib.s"
	@echo "... decomposition/Treat/Treat.o"
	@echo "... decomposition/Treat/Treat.i"
	@echo "... decomposition/Treat/Treat.s"
	@echo "... decomposition/Treat/equalizer.o"
	@echo "... decomposition/Treat/equalizer.i"
	@echo "... decomposition/Treat/equalizer.s"
	@echo "... decomposition/Treat/previewEqua.o"
	@echo "... decomposition/Treat/previewEqua.i"
	@echo "... decomposition/Treat/previewEqua.s"
	@echo "... decomposition/fft.o"
	@echo "... decomposition/fft.i"
	@echo "... decomposition/fft.s"
	@echo "... decomposition/main.o"
	@echo "... decomposition/main.i"
	@echo "... decomposition/main.s"
	@echo "... file_decoder/wav/Decoder/WavDecoder.o"
	@echo "... file_decoder/wav/Decoder/WavDecoder.i"
	@echo "... file_decoder/wav/Decoder/WavDecoder.s"
	@echo "... file_decoder/wav/Decoder/decoderWavHeader.o"
	@echo "... file_decoder/wav/Decoder/decoderWavHeader.i"
	@echo "... file_decoder/wav/Decoder/decoderWavHeader.s"
	@echo "... file_decoder/wav/Recoder/WavRecoder.o"
	@echo "... file_decoder/wav/Recoder/WavRecoder.i"
	@echo "... file_decoder/wav/Recoder/WavRecoder.s"
	@echo "... file_decoder/wav/tools/WavChecker.o"
	@echo "... file_decoder/wav/tools/WavChecker.i"
	@echo "... file_decoder/wav/tools/WavChecker.s"
	@echo "... file_decoder/wav/tools/WavTools.o"
	@echo "... file_decoder/wav/tools/WavTools.i"
	@echo "... file_decoder/wav/tools/WavTools.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mainUI.o"
	@echo "... mainUI.i"
	@echo "... mainUI.s"
	@echo "... testGraph.o"
	@echo "... testGraph.i"
	@echo "... testGraph.s"
	@echo "... wavelib/auxiliary/denoise.o"
	@echo "... wavelib/auxiliary/denoise.i"
	@echo "... wavelib/auxiliary/denoise.s"
	@echo "... wavelib/auxiliary/waux.o"
	@echo "... wavelib/auxiliary/waux.i"
	@echo "... wavelib/auxiliary/waux.s"
	@echo "... wavelib/src/conv.o"
	@echo "... wavelib/src/conv.i"
	@echo "... wavelib/src/conv.s"
	@echo "... wavelib/src/cwt.o"
	@echo "... wavelib/src/cwt.i"
	@echo "... wavelib/src/cwt.s"
	@echo "... wavelib/src/cwtmath.o"
	@echo "... wavelib/src/cwtmath.i"
	@echo "... wavelib/src/cwtmath.s"
	@echo "... wavelib/src/hsfft.o"
	@echo "... wavelib/src/hsfft.i"
	@echo "... wavelib/src/hsfft.s"
	@echo "... wavelib/src/real.o"
	@echo "... wavelib/src/real.i"
	@echo "... wavelib/src/real.s"
	@echo "... wavelib/src/wavefilt.o"
	@echo "... wavelib/src/wavefilt.i"
	@echo "... wavelib/src/wavefilt.s"
	@echo "... wavelib/src/wavefunc.o"
	@echo "... wavelib/src/wavefunc.i"
	@echo "... wavelib/src/wavefunc.s"
	@echo "... wavelib/src/wavelib.o"
	@echo "... wavelib/src/wavelib.i"
	@echo "... wavelib/src/wavelib.s"
	@echo "... wavelib/src/wtmath.o"
	@echo "... wavelib/src/wtmath.i"
	@echo "... wavelib/src/wtmath.s"
	@echo "... wavlet/Wavelet.o"
	@echo "... wavlet/Wavelet.i"
	@echo "... wavlet/Wavelet.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

